"""add_stages_snapshot_to_plan_run

Revision ID: 0e8db5c5137c
Revises: 000006
Create Date: 2026-03-11 14:55:21.653080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e8db5c5137c'
down_revision = '000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olh_approval_rule')
    op.alter_column('olh_plan', 'status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('ready', 'suspended', 'running', name='planstatus', native_enum=False),
               comment=None,
               existing_comment='计划状态',
               existing_nullable=False)
    op.alter_column('olh_plan', 'exec_type',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('manual', 'cron', 'fixed', name='planexectype', native_enum=False),
               comment=None,
               existing_comment='执行类型',
               existing_nullable=False)
    op.add_column('olh_plan_run', sa.Column('stages_snapshot', mysql.JSON(), nullable=True, comment='执行时的 Stages 快照'))
    op.alter_column('olh_plan_run', 'status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('preparing', 'running', 'succeeded', 'failed', 'stopped', 'suspended', 'duplicated', name='planrunstatus', native_enum=False),
               comment=None,
               existing_comment='执行状态',
               existing_nullable=False)
    op.alter_column('olh_run', 'engine_type',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('jmeter', 'k6', 'custom', name='enginetype', native_enum=False),
               existing_comment='引擎类型',
               existing_nullable=False)
    op.alter_column('olh_run', 'run_status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('preparing', 'running', 'succeeded', 'failed', 'stopped', name='runstatus', native_enum=False),
               comment=None,
               existing_comment='主状态',
               existing_nullable=False)
    op.drop_index(op.f('idempotency_key'), table_name='olh_run')
    op.drop_index(op.f('ix_olh_run_idempotency_key'), table_name='olh_run')
    op.create_index(op.f('ix_olh_run_idempotency_key'), 'olh_run', ['idempotency_key'], unique=True)
    op.alter_column('olh_task', 'status',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Enum('draft', 'pending_submit_approval', 'ready', 'script_missing', 'awaiting_approval', 'approval_rejected', 'running', name='taskstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('olh_task', 'engine_type',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('jmeter', 'k6', 'custom', name='enginetype', native_enum=False),
               comment='引擎类型',
               existing_nullable=False)
    op.alter_column('olh_task', 'task_pattern',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Enum('script', 'visualization', name='taskpattern', native_enum=False),
               comment=None,
               existing_comment='任务模式（script/visualization）',
               existing_nullable=False)
    op.drop_column('olh_task', 'finished_at')
    op.drop_column('olh_task', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olh_task', sa.Column('started_at', mysql.DATETIME(), nullable=True))
    op.add_column('olh_task', sa.Column('finished_at', mysql.DATETIME(), nullable=True))
    op.alter_column('olh_task', 'task_pattern',
               existing_type=sa.Enum('script', 'visualization', name='taskpattern', native_enum=False),
               type_=mysql.VARCHAR(length=64),
               comment='任务模式（script/visualization）',
               existing_nullable=False)
    op.alter_column('olh_task', 'engine_type',
               existing_type=sa.Enum('jmeter', 'k6', 'custom', name='enginetype', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='引擎类型',
               existing_nullable=False)
    op.alter_column('olh_task', 'status',
               existing_type=sa.Enum('draft', 'pending_submit_approval', 'ready', 'script_missing', 'awaiting_approval', 'approval_rejected', 'running', name='taskstatus', native_enum=False),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_olh_run_idempotency_key'), table_name='olh_run')
    op.create_index(op.f('ix_olh_run_idempotency_key'), 'olh_run', ['idempotency_key'], unique=False)
    op.create_index(op.f('idempotency_key'), 'olh_run', ['idempotency_key'], unique=True)
    op.alter_column('olh_run', 'run_status',
               existing_type=sa.Enum('preparing', 'running', 'succeeded', 'failed', 'stopped', name='runstatus', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               comment='主状态',
               existing_nullable=False)
    op.alter_column('olh_run', 'engine_type',
               existing_type=sa.Enum('jmeter', 'k6', 'custom', name='enginetype', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               existing_comment='引擎类型',
               existing_nullable=False)
    op.alter_column('olh_plan_run', 'status',
               existing_type=sa.Enum('preparing', 'running', 'succeeded', 'failed', 'stopped', 'suspended', 'duplicated', name='planrunstatus', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               comment='执行状态',
               existing_nullable=False)
    op.drop_column('olh_plan_run', 'stages_snapshot')
    op.alter_column('olh_plan', 'exec_type',
               existing_type=sa.Enum('manual', 'cron', 'fixed', name='planexectype', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               comment='执行类型',
               existing_nullable=False)
    op.alter_column('olh_plan', 'status',
               existing_type=sa.Enum('ready', 'suspended', 'running', name='planstatus', native_enum=False),
               type_=mysql.VARCHAR(length=32),
               comment='计划状态',
               existing_nullable=False)
    op.create_table('olh_approval_rule',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False, comment='规则名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='规则描述'),
    sa.Column('condition_type', mysql.ENUM('ENV', 'THREAD_COUNT', 'DURATION', 'ENGINE_TYPE', 'ALWAYS'), nullable=False, comment='条件类型'),
    sa.Column('condition_op', mysql.ENUM('EQ', 'NEQ', 'GT', 'GTE', 'LT', 'LTE', 'IN'), server_default=sa.text("'EQ'"), nullable=False, comment='条件操作符'),
    sa.Column('condition_value', mysql.VARCHAR(length=500), nullable=False, comment='条件值（字符串，多值逗号分隔）'),
    sa.Column('approver_roles', mysql.JSON(), nullable=True, comment='审批角色列表 JSON'),
    sa.Column('priority', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='优先级（数字越大优先级越高）'),
    sa.Column('enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
