from pathlib import Path
import sys

COMMON_PARENT = Path(__file__).resolve().parents[3]
if COMMON_PARENT.exists():
    sys.path.append(str(COMMON_PARENT))

from common.schemas.script import (  # type: ignore
    AIK6ScriptDraftRequest,
    AIK6ScriptDraftResponse,
    AIK6ScriptReviewHumanFeedback,
    AIK6ScriptReviewRequest,
    AIK6ScriptReviewResponse,
    AIK6ScriptReviewRiskItem,
    AIK6ScriptStaticFinding,
    CurlToK6FieldItem,
    CurlToK6ParsedRequest,
    CurlToK6PreviewResponse,
    CurlToK6ScriptCreate,
    CurlToK6ScriptCreateResponse,
    CurlToK6VariableSuggestion,
    HarToK6EntryItem,
    HarToK6ParsedRequest,
    HarToK6PreviewResponse,
    HarToK6ScriptCreate,
    HarToK6ScriptCreateResponse,
    HarToK6SpecParseRequest,
    HarToK6SpecParseResponse,
    OpenApiToK6EndpointItem,
    OpenApiToK6ParsedRequest,
    OpenApiToK6PreviewResponse,
    OpenApiToK6ScriptCreate,
    OpenApiToK6ScriptCreateResponse,
    OpenApiToK6SpecParseRequest,
    OpenApiToK6SpecParseResponse,
    ScriptCreate,
    ScriptContentUpdate,
    ScriptListResponse,
    ScriptResponse,
    ScriptStatus,
    ScriptType,
    ScriptUpdate,
)

__all__ = [
    "AIK6ScriptDraftRequest",
    "AIK6ScriptDraftResponse",
    "AIK6ScriptReviewHumanFeedback",
    "AIK6ScriptReviewRequest",
    "AIK6ScriptReviewResponse",
    "AIK6ScriptReviewRiskItem",
    "AIK6ScriptStaticFinding",
    "CurlToK6FieldItem",
    "CurlToK6ParsedRequest",
    "CurlToK6PreviewResponse",
    "CurlToK6ScriptCreate",
    "CurlToK6ScriptCreateResponse",
    "CurlToK6VariableSuggestion",
    "HarToK6EntryItem",
    "HarToK6ParsedRequest",
    "HarToK6PreviewResponse",
    "HarToK6ScriptCreate",
    "HarToK6ScriptCreateResponse",
    "HarToK6SpecParseRequest",
    "HarToK6SpecParseResponse",
    "OpenApiToK6EndpointItem",
    "OpenApiToK6ParsedRequest",
    "OpenApiToK6PreviewResponse",
    "OpenApiToK6ScriptCreate",
    "OpenApiToK6ScriptCreateResponse",
    "OpenApiToK6SpecParseRequest",
    "OpenApiToK6SpecParseResponse",
    "ScriptCreate",
    "ScriptContentUpdate",
    "ScriptListResponse",
    "ScriptResponse",
    "ScriptStatus",
    "ScriptType",
    "ScriptUpdate",
]
